import { Outfit, Inter } from "next/font/google";

import "./globals.css";
import ReactLenis from "lenis/react";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Adquora",
  description: "Generated by yashsrivasta7a",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${outfit.variable} ${inter.variable} font-sans`}>
        <ReactLenis root>
          <div className="min-h-screen">
            {children}
          </div>
        </ReactLenis>
      </body>
    </html>
  );
}
